### ISSUE TITLE
Modifying SASS files triggers full reload since 2.6.2

### ISSUE THREAD

**Issue by Timbuktu1982** [embroider-build/ember-auto-import#577]
Hi there, 

modifying a SASS file causes full page reload instead of CSS livereload in Ember since ember-auto-import 2.6.2. It wasn't the case when I was using 2.6.1 previously.

Thx

**Comment by KoKuToru** [comment]
Since 2.6.2 the code writes new js-files for each build https://github.com/embroider-build/ember-auto-import/blob/v2.6.3/packages/ember-auto-import/ts/webpack.ts#L366

These files don't get cached like in https://github.com/embroider-build/ember-auto-import/blob/v2.6.3/packages/ember-auto-import/ts/inserter.ts#L228

From my testing .. caching these files should solve the reload problem..

**Comment by erkie** [comment]
However, it looks like even if I just make changes to `.ts` files now, it still sends a reload on the css file. I added some logging:

```
send reload: [ 'assets/frontend.css', 'assets/frontend.js' ]
```

This was when I only changed a typescript file. Still better than a page reload on simple CSS changes.

**Comment by Timbuktu1982** [comment]
Hello everyone,
Is there any new information on this topic?

**Comment by sly7-7** [comment]
This is still happening with ember-auto-import 2.7.2, though a new app with embroider doesn't have this problem.

**Comment by pikilipita** [comment]
Having the same issue on my Ember projects

**Comment by pikilipita** [comment]
This is still happening with ember-auto-import 2.7.4 and I cannot downgrade to 2.6.1, while using ember 5.8.0, 
any workaround suggestions?

**Comment by mweidner037** [comment]
If you downgrade to 2.6.1 due to this issue, you may need some additional configuration to get 2.6.1 to play nicely with newer dependencies. This is what worked for our app: in `ember-cli-build.js`, add EmberApp option
```js
    autoImport: {
      webpack: {
        module: {
          rules: [
            {
              test: /\.m?js$/,
              use: {
                loader: "babel-loader",
                options: {
                  // This is needed with ember-auto-import 2.6.1 because some of our deps export newer JS
                  // (see https://github.com/embroider-build/ember-auto-import/issues/482#issuecomment-1007086422).
                  plugins: ["@babel/plugin-transform-class-static-block"],
                },
              },
            },
          ],
        },
      },
      // This is needed with ember-auto-import 2.6.1 (and maybe other versions?) or else
      // the whole app stops working, but only in the prod build!
      // "(0 , r.tracked) is not a function"
      // Fix from https://github.com/embroider-build/ember-auto-import/issues/564#issuecomment-1448820349
      earlyBootSet: () => ["@glimmer/tracking"],
    },
```

**Comment by Timbuktu1982** [comment]
Greatful... THX

**Comment by apellerano-pw** [comment]
@yads there should be no additional config needed. The fix in #664 added a caching layer to prevent disk write when certain JS file contents don't change. (No JS disk write, no livereload trigger.)

If you're still getting full reloads, I would investigate what in your build is writing JS to disk when all you've modified is SASS files. There may be another JS cache that has to be added to ember-auto-import, or perhaps another lib/addon you use that is sensitive to SASS changes and needs a better cache.
